[book]
authors = ["Mohsen"]
language = "en"
multilingual = false
src = "src"
title = "JungoAI Book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
git-repository-url = "https://github.com/jungoai/jungo-book"
git-repository-icon = "fa-github"
